name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.11.1
  - netcdf4=1.6.0
  - python>=3.8
  - pandas=1.4.4
  - pip=24.0
  - richdem=2.3.0
  - rasterio=1.2.10
  - rioxarray=0.12.0
  - scikit-learn=1.1.2
  - typing=3.10.0.0
  - xarray=2022.6.0
  - pip:
    - numpy==1.23
    - geojson==2.5.0
    - scikit-image==0.24.0
    - seaborn==0.13.2
    - xarray-spatial==0.4.0
    - resreg==0.2